session:
  name: session_id
  secret_key: abc123
db:
  default:
    type: postgres
    host: 192.168.127.128
    port: 5432
    user: postgres
    password: 123456
    dbname: hananoq_blog
redis:
  default:
    addr: 192.168.127.128:6379
    password:
    db: 0
  request:
    addr: 192.168.127.128:6379
    password:
    db: 1
oauth2:
  client:
    - id: test_client_1
      secret: devil_may_cry_five
      name: test_app1
      domain: http://localhost:9696
      scope:
        - id: all
          title: account, smarthome, permission, role etc
# 放行的路由(包含就放行)
release_router:
  - /auth/login
  - /auth/token
  - /auth/noLogout
  - /auth/register
  - /article
  - /music
  - /friend-address/getFriendAddress
  - /comment
  - /category

OSS:
  endpoint: '<your endpoint>'
  region: '<your region>'
  accessKeyId: '<your accessKeyId>'
  accessKeySecret: '<your accessKeySecret>'
  bucket: '<your bucket>'
# 用于签名验证，TODO
sign:
  app_id: 9dsa79792313
  nonce: dsafsadjgsdaf
  secret: da4sf6ds4f6asd4